### ISSUE TITLE
Which is the query in the Nordland dataset?

### ISSUE THREAD

**Issue by DonMuv** [oravus/DeltaDescriptors#1]
Hi,
I’m not sure if summer is the query or winter is the query within Nordland dataset
Thanks

**Comment by oravus** [comment]
Hi @DonMuv,

For the Nordland dataset, we used the summer traverse as the reference and winter as the query.

On a side note, you can also look at our recent [SeqNet code](https://github.com/oravus/seqNet) for a gpu-based implementation of Delta Descriptors.

**Comment by oravus** [comment]
Hi, hope the above resolves your issue. Please feel free to re-open if it needs be.
